AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'lib/generators/**/*'
    - 'tmp/**/*'
    - 'spec/**/*'
    - 'vendor/**/*' # added by github actions

Style/Documentation:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Layout/LineLength:
  Max: 125

Lint/MissingSuper:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Enabled: false

Metrics/ParameterLists:
  Max: 10

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required
